# Generated by Django 5.1 on 2024-09-15 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('grand_father_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('general_directorate', models.CharField(max_length=50)),
                ('directorate', models.CharField(max_length=50)),
                ('head', models.CharField(max_length=50)),
                ('job_position', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=255)),
                ('staus', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('degree', models.CharField(choices=[('H', 'High School'), ('B', 'Bachelor'), ('M', 'Master'), ('P', 'Phd'), ('A', 'Associate Professor')], default='B', max_length=1)),
                ('mraital_status', models.CharField(choices=[('S', 'SingleM'), ('M', 'Married'), ('W', 'Widdow')], max_length=1)),
                ('gender', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('report', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('fee', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('test', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.country')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.province')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_start_data', models.DateField()),
                ('job_end_date', models.DateField()),
                ('remarks', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.country')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.department')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.grade')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.jobposition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.organization')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.organizationtype')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.province')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.status')),
                ('step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.step')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_start_date', models.DateField()),
                ('education_end_date', models.DateField()),
                ('batch_no', models.CharField(max_length=50)),
                ('education_remarks', models.CharField(max_length=500)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.country')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.degree')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.faculty')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.major')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.university')),
            ],
        ),
    ]
