# Generated by Django 5.1 on 2024-09-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='test',
        ),
    ]
